language: c
install:
    - sudo apt-get update
    - sudo apt-get -y install libssl-dev libexpat1-dev libncursesw5-dev libglib2.0-dev libnotify-dev libcurl3-dev libxss-dev libotr2-dev
    - git clone git://github.com/strophe/libstrophe.git
    - cd libstrophe
    - mkdir m4
    - ./bootstrap.sh
    - ./configure --prefix=/usr
    - make
    - sudo make install
    - cd ..
    - rm -rf libstrophe
    - wget https://open.cryptomilk.org/attachments/download/42/cmocka-0.4.1.tar.xz
    - tar -xvf cmocka-0.4.1.tar.xz
    - cd cmocka-0.4.1
    - mkdir build
    - cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Debug ..
    - make
    - sudo make install
    - cd ../..
    - rm -rf cmocka-0.4.1
    - ./bootstrap.sh
script: ./configure && make && make check
